Repository Netcracker/qubership-integration-runtime-catalog, pull requests merged in 2025-07, with the labels that each got.

#120 feat: Updated import/export format to match new schemas
  src/main/java/org/qubership/integration/platform/runtime/catalog/model/exportimport/system/IntegrationSystemContentDto.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/model/exportimport/system/IntegrationSystemDto.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/model/exportimport/system/SpecificationGroupContentDto.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/model/exportimport/system/SpecificationGroupDto.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/model/exportimport/system/SpecificationSourceDto.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/model/exportimport/system/SystemModelContentDto.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/model/exportimport/system/SystemModelDto.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/ChainImportService.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/ExportImportConstants.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/ImportService.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/SystemExportImportService.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/deserializer/ServiceDeserializer.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/mapper/chain/ChainExternalEntityMapper.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/mapper/services/IntegrationSystemDtoMapper.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/mapper/services/SpecificationGroupDtoMapper.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/mapper/services/SystemModelDtoMapper.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/FileMigrationService.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/MigrationException.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/chain/ChainFileMigrationService.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/chain/V101ChainImportFileMigration.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/chain/versions/ChainFileVersionsGetterService.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/chain/versions/ChainFileVersionsGetterStrategy.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/chain/versions/strategies/MigrationFieldInContentStrategy.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/chain/versions/strategies/VersionFieldStrategy.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/common/V101MigrationUtil.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/system/V101ServiceImportFileMigration.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/versions/VersionsGetterService.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/versions/VersionsGetterStrategy.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/versions/strategies/MigrationFieldInContentStrategy.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/versions/strategies/MigrationFieldStrategy.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/migrations/versions/strategies/VersionFieldStrategy.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/serializer/ServiceSerializer.java
  src/main/resources/application.yml
Labels: enhancement

#130 fix: #129 Fixed the STARTS_WITH condition for filter
  src/main/java/org/qubership/integration/platform/runtime/catalog/model/filter/FilterCondition.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/persistence/configs/repository/actionlog/ActionLogFilterRepositoryImpl.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/persistence/configs/repository/chain/ElementFilterRepositoryImpl.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/filter/ChainFilterSpecificationBuilder.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/filter/FilterConditionPredicateBuilderFactory.java
Labels: bug

#132 feat: Updated spring lib versions
  pom.xml
Labels: enhancement, feature

#138 fix: fixed import of service
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/deserializer/ServiceDeserializer.java
Labels: bug
