Repository Netcracker/qubership-integration-runtime-catalog, pull requests merged in 2025-09, with the labels that each got.

#185 feat: groupId updated to org.qubership.integration.platform
  pom.xml
Labels: enhancement, feature

#133 fix(ci): fix for link-checker workflow [skip ci]
  .github/workflows/link-checker.yaml
Labels: bug

#193 feat: #192 Remove maskingEnabled field in chain export
  src/main/java/org/qubership/integration/platform/runtime/catalog/model/exportimport/chain/ChainExternalContentEntity.java
  src/main/java/org/qubership/integration/platform/runtime/catalog/service/exportimport/ExportImportConstants.java
  src/test/java/org/qubership/integration/platform/runtime/catalog/testutils/dto/ChainImportDTO.java
  src/test/resources/testData/input/service/dependency/chain.yml
  src/test/resources/testData/input/service/migration/basic_scenario.yaml
  src/test/resources/testData/input/service/migration/element/async_split_element.yaml
  src/test/resources/testData/input/service/migration/element/catch.yaml
  src/test/resources/testData/input/service/migration/element/circuit_breaker_configuration.yaml
  src/test/resources/testData/input/service/migration/element/finally.yaml
  src/test/resources/testData/input/service/migration/element/loop.yaml
  src/test/resources/testData/input/service/migration/element/main_split_element.yaml
  src/test/resources/testData/input/service/migration/element/on_fallback.yaml
  src/test/resources/testData/input/service/migration/element/otherwise.yaml
  src/test/resources/testData/input/service/migration/element/split_element.yaml
  src/test/resources/testData/input/service/migration/element/try.yaml
  src/test/resources/testData/input/service/migration/element/when.yaml
  src/test/resources/testData/output/service/migration/basic_scenario.yaml
  src/test/resources/testData/output/service/migration/element/async_split_element.yaml
  src/test/resources/testData/output/service/migration/element/catch.yaml
  src/test/resources/testData/output/service/migration/element/circuit_breaker_configuration.yaml
  src/test/resources/testData/output/service/migration/element/finally.yaml
  src/test/resources/testData/output/service/migration/element/loop.yaml
  src/test/resources/testData/output/service/migration/element/main_split_element.yaml
  src/test/resources/testData/output/service/migration/element/on_fallback.yaml
  src/test/resources/testData/output/service/migration/element/otherwise.yaml
  src/test/resources/testData/output/service/migration/element/split_element.yaml
  src/test/resources/testData/output/service/migration/element/try.yaml
  src/test/resources/testData/output/service/migration/element/when.yaml
Labels: enhancement
